### signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "name": "test SignUp",
  "email": "signup1@test.com",
  "password": "test"
}

### signin
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "signup6@test.com",
  "password": "test"
}

### current user
GET http://localhost:3000/auth/current-user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCBTaWduVXAiLCJlbWFpbCI6InNpZ251cDFAdGVzdC5jb20iLCJwYXNzd29yZCI6ImUyY2Q3OWVkYjM1NzdjYTUuZGEwNDQwMGMzZmY2ODBkMTc4M2YwZWZkMzAyMGQ4NWZiZDdlY2Q5MmMyZTM5Y2RkNzc2ZDUxZjA1NWRmNjA4YyIsImlkIjoxLCJjcmVhdGVkX2F0IjoiMjAyNC0wMS0xNVQwMzoxNzo0NS40MDdaIiwidXBkYXRlZF9hdCI6IjIwMjQtMDEtMTVUMDM6MTc6NDUuNDA3WiIsImlhdCI6MTcwNTI4ODY2NX0.3t5FHsARNYfrPRlBfQbD0qq6fhjtfU7zh3mH7fVaVFI