### =====> CREATE VA LINKQU <===== ###
### create VA Permata
POST http://localhost:3000/virtual-account
Content-Type: application/json

{
  "amount" : 30000,
	"partner_reff" : "200102083952237461",
	"customer_id" : "31857118",
	"customer_name" : "GPI LINKQU",
	"expired" : "20240222150000",
	"username" : "LI307GXIN",
	"pin" : "2K2NPCBBNNTovgB",
	"customer_phone" : "081231857418",
	"customer_email" : "pay@linkqu.id",
  "bank_code" : "013",
  "url_callback" : "https://webhook.site/022ea05b-02af-4b77-b868-b291d32699e8"
}

### create va other bank
POST http://localhost:3000/virtual-account/va-other-bank
Content-Type: application/json

{
  "expired": "20240124160000",
  "amount": 10000,
  "customer_id": "31857118",
  "partner_reff": "200102083952562712182",
  "customer_phone": "081231857418",
  "customer_email": "pay@linkqu.id",
  "bank_code": "002",
  "username": "LI307GXIN",
  "pin": "2K2NPCBBNNTovgB",
  "customer_name": "PAY GPI",
  "remark": "test satu"
}

### create va dedicated
POST http://localhost:3000/virtual-account/va-dedicated
Content-Type: application/json

{
  "customer_id": "31857119",
  "customer_phone": "081231857418",
  "customer_name": "PAY GPI",
  "customer_email": "pay@linkqu.id",
  "bank_code": "002",
  "username": "LI307GXIN",
  "pin": "2K2NPCBBNNTovgB",
  "is_custom": false
}

### update va dedicated
PUT http://localhost:3000/virtual-account/va-dedicated
Content-Type: application/json

{
  "customer_id": "31857118",
  "customer_phone": "081231857418",
  "customer_name": "PAY GPI",
  "customer_email": "pay@linkqu.id",
  "bank_code": "002",
  "username": "LI307GXIN",
  "pin": "2K2NPCBBNNTovgB",
  "is_custom": false
}

// ==========

### get va bank
GET http://localhost:3000/virtual-account?amount=30000&partner_reff=200102083952237456&customer_id=31857118&customer_name=GPI LINKQU&expired=20240122150000&username=LI307GXIN&pin=2K2NPCBBNNTovgB&customer_phone=081231857418&customer_email=pay@linkqu.id&bank_code=013&url_callback=https://url_callback_partner.com
Content-Type: application/json

### craete VA permata
GET http://localhost:3000/virtual-account

###
POST https://gateway-dev.linkqu.id/linkqu-partner/transaction/create/va
Content-Type: application/json
client-id: testing
client-secret: 123

{
  "expired": "20230225230000",
  "amount": 10000,
  "customer_id": "31857118",
  "partner_reff": "200102083952562712182",
  "customer_phone": "081231857418",
  "customer_email": "pay@linkqu.id",
  "bank_code": "002",
  "username": "LI307GXIN",
  "pin": "2K2NPCBBNNTovgB",
  "customer_name": "PAY GPI",
  "remark": "test satu",
  "signature": "569dbd2a54cb99dac4c8e9818dc1522ce0a892460ef0b2e5c2bd0e1b0a0c560f",
  "url_callback": "https://cognos.linkqu.id"
}